name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: 3.7

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.6.4

    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir dist
      env:
        # build just python 3.7
        CIBW_BUILD: cp37-* cp38-* cp39-*
        # we need boost
        # we need pybind11 to be globally available for cibuildwheel
        CIBW_BEFORE_BUILD_LINUX: pip install --upgrade pip
        CIBW_BEFORE_BUILD_MACOS: python -m pip install --upgrade pip
        CIBW_BEFORE_BUILD_WINDOWS: python -m pip install --upgrade pip
        CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.14
        #CIBW_TEST_REQUIRES: pytest
        #CIBW_TEST_COMMAND: py.test -v {project}/tests
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist
